name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
concurrency:
  # head_ref for PRs is the branch name, for main it is an empty string. run_id is unique for each run.
  # This way we will cancel ongoing runs for PRs (to save $), but we will perform all runs for main.
  group:  ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/ci_lint.yml
  typecheck:
    uses: ./.github/workflows/ci_typecheck.yml
  test:
    uses: ./.github/workflows/ci_test.yml
    needs: [lint, typecheck]
  build:
    uses: ./.github/workflows/ci_build.yml
    needs: [lint, typecheck]
